CREATE TABLE Label (
    id SERIAL PRIMARY KEY,
    title VARCHAR(50),
    color VARCHAR(50)
);

CREATE TABLE Item (
    id SERIAL PRIMARY KEY,
    label_id INT REFERENCES Label(id),
    publish_date DATE NOT NULL,
    archived BOOLEAN NOT NULL
);


CREATE TABLE Book (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher VARCHAR(50),
    cover_state VARCHAR(20)
) INHERITS (Item);
